spring:
  application:
    name: atomix-cafeteria
  
  # H2 Database Configuration for testing
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  # JPA Configuration for H2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Disable Flyway for testing
  flyway:
    enabled: false
  
  # Disable OAuth2 for testing
  security:
    oauth2:
      client:
        registration: {}

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /api/v1

# Application Specific Configuration
app:
  jwt:
    secret: testSecretKey
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days

# Logging Configuration
logging:
  level:
    com.atomix.cafeteria: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 